# -*- coding: utf-8 -*-
"""Assignment_09 (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvVfCm69Zc7AwbYztqSamaph81xKn3Nh

Assignment 09:  Use an AI-based tool to generate simple video animations.

Install Required Libraries
"""

!pip install diffusers transformers accelerate torch moviepy imageio

"""Import Libraries"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from diffusers import StableDiffusionPipeline
from moviepy.editor import ImageSequenceClip
from IPython.display import Video

"""Load the Model

Using Stable Diffusion from Hugging Face.
"""

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

"""Create Animation Prompts"""

prompts = [
    "cute robot standing in futuristic city",
    "cute robot walking in futuristic city",
    "cute robot waving hand in futuristic city",
    "cute robot jumping happily in futuristic city",
    "cute robot flying with jetpack in futuristic city"
]

Generate Frames

frames = []

for p in prompts:

    image = pipe(p).images[0]

    frames.append(np.array(image))

    plt.figure()
    plt.imshow(image)
    plt.axis("off")

"""Create Video Animation"""

clip = ImageSequenceClip(frames, fps=1)

clip.write_videofile("ai_animation.mp4")

"""Display the Video"""

Video("ai_animation.mp4", embed=True)